resources:
  - name: Git_PH
    type: GitRepo
    configuration:
      gitProvider: PasswordHunterGit                      
      path: liavgu/Multi_threaded_online_brute_force_template    
      branches:
        include: master
      buildOn:
        commit: true
#
  - name: PasswordHunter_base_docker_image
    type: Image
    configuration:
      registry: MyArtifactory                                
      sourceRepository: base-images               
      imageName: base_image
      imageTag: "1"
      autoPull: true
      
  - name: PasswordHunter_Prod
    type: Image
    configuration:
      registry: MyArtifactory                                
      sourceRepository: base-images               
      imageName: PasswordHunter
      imageTag: ${run_number}
      autoPull: true

  - name: py_app_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: MyArtifactory

pipelines:
  - name: PH_V4
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: build_push
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: avigdor.jfrog.io/base-images/base_image
          dockerImageTag: "1"
          inputResources:
            - name: Git_PH
          integrations:
            - name: MyArtifactory                           

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: build_push
          targetRepository: prod-repo
          integrations:
            - name: MyArtifactory                            
          inputSteps:
            - name: docker_build
          outputResources:
            - name: PasswordHunter_Prod

      - name: publish_app_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: py_app_buildinfo

      - name: xrayScanStep
        type: XrayScan
        configuration:
          inputResources:
           - name: py_app_buildinfo
