resources:
  - name: Git_Golda
    type: GitRepo
    configuration:
      gitProvider: GoldaGit                      
      path: liavgu/Multi_threaded_online_brute_force_template    
      branches:
        include: master
      buildOn:
        commit: true
#
  - name: golda_new_docker_image
    type: Image
    configuration:
      registry: MyArtifactory                                
      sourceRepository: prod-repo               
      imageName: liavgoldadev.jfrogdev.org/prod-repo/golda
      imageTag: ${run_number}
      autoPull: true

  - name: py_app_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: MyArtifactory

pipelines:
  - name: golda_pipeline_v2
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: build_push
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: liavgoldadev.jfrogdev.org/prod-repo/golda 
          dockerImageTag: ${run_number}
          inputResources:
            - name: Git_Golda
          integrations:
            - name: MyArtifactory                           

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: build_push
          targetRepository: prod-repo
          integrations:
            - name: MyArtifactory                            
          inputSteps:
            - name: docker_build
          outputResources:
            - name: golda_new_docker_image

      - name: publish_app_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: py_app_buildinfo

      - name: xrayScanStep
        type: XrayScan
        configuration:
          inputResources:
           - name: py_app_buildinfo