resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: webappgit                       # <-- replace with your integration
      path: liavgu/jfrog-pipelines-docker-sample    # <-- replace with your repository name
      branches:
        include: master

  - name: new_image_name
    type: Image
    configuration:
      registry: MyArtifactory                                # <-- replace with your     MyArtifactoryifactory integration
      sourceRepository: prod-repo               # <-- required if registry is     MyArtifactoryifactory
      imageName: liavacademy.jfrogdev.org/prod-repo/webinfra # < -- replace with your image path and name
      imageTag: ${run_number}
      autoPull: true
      

pipelines:
  - name: pipeline_build_and_push_liav
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: liavacademy.jfrogdev.org/prod-repo/webinfra  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo
          integrations:
            - name: MyArtifactory                            # <-- replace with your     MyArtifactoryifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: liav-local-repo
          integrations:
            - name: MyArtifactory                            # <-- new test replace with your     MyArtifactoryifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: new_image_name