resources:
  - name: Git_Golda
    type: GitRepo
    configuration:
      gitProvider: GoldaGit                       # <-- replace wth your 
      path: liavgu/Multi_threaded_online_brute_force_template    # <-- replace with your repository name
      branches:
        include: master

  - name: new_docker_image_
    type: Image
    configuration:
      registry: MyArtifactory                                # <-- replace with your     MyArtifactoryifactory integration
      sourceRepository: prod-repo               # <-- required if registry is     MyArtifactoryifactory
      imageName: liavgoldadev.jfrogdev.org/prod-repo/webinfra # < -- replace with your image path and name
      imageTag: ${run_number}
      autoPull: true

  - name: py_app_buildinfo_
    type: BuildInfo
    configuration:
      sourceArtifactory: MyArtifactory

  - name: py_app_promoted_buildinfo_
    type: BuildInfo
    configuration:
      sourceArtifactory: MyArtifactory 

pipelines:
  - name: golda_pipeline
    steps:
      - name: docker_build_
        type: DockerBuild
        configuration:
          affinityGroup: build_push
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: liavacademy.jfrogdev.org/prod-repo/webinfra  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: Git_Golda
          integrations:
            - name: MyArtifactory                            # <-- replace with your     MyArtifactoryifactory integration

      - name: docker_push_
        type: DockerPush
        configuration:
          affinityGroup: build_push
          targetRepository: liav-local-repo
          integrations:
            - name: MyArtifactory                            # <-- new test replace with your     MyArtifactoryifactory integration
          inputSteps:
            - name: docker_build_
          outputResources:
            - name: new_docker_image_

      - name: publish_app_build_
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push_
          outputResources:
            - name: py_app_buildinfo_

      - name: xrayScanStep
        type: XrayScan
        configuration:
          inputResources:
            - name: py_app_buildinfo_